### ISSUE TITLE
Leaders_Eat_Last.jpg and Simon_Sinek.jpg

### ISSUE THREAD

**Issue by MrDi0nysus** [DavidGeeraerts/Leadership#3]
![Leaders_Eat_Last](https://user-images.githubusercontent.com/19692374/142661968-737624b3-bf1f-46dd-85b2-aaadbd4e4c4f.jpg)

**Comment by MrDi0nysus** [comment]
![Simon_Sinek](https://user-images.githubusercontent.com/19692374/142661410-189c24a8-b29b-49c8-b25b-a8deb43c490f.jpg)

**Comment by DavidGeeraerts** [comment]
Thanks for getting these.
Just a note: when getting these, try to get them with CC license.
Just about all images on Wikipedia are [CC](https://creativecommons.org/)
 Added to Main Branch.
